openapi: 3.0.3
info:
  title: Basic Form Submission API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /submit-form:
    post:
      summary: Submit a form
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the user
              required:
                - name
      responses:
        '200':
          description: Form submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Form submitted successfully!