openapi: 3.0.0
info:
  title: Repair Service
  description: A simple service to manage repairs
  version: 1.0.0
servers:
  - url: https://sme85beaf.azurewebsites.net/api
    description: The repair api server
paths:
  /repairs:
    post:
      operationId: createRepair
      summary: Create a new repair
      description: Creates a new repair with the provided details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The short summary of the repair
                description:
                  type: string
                  description: The detailed description of the repair
                assignedTo:
                  type: string
                  description: The user who is responsible for the repair
                details:
                  type: object
                  description: Additional details about the repair
                  properties:
                    partNumber:
                      type: string
                      description: The part number of the item to be repaired
                    warranty:
                      type: boolean
                      description: Whether the item is under warranty
      responses:
        '201':
          description: Repair created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the created repair
                  title:
                    type: string
                    description: The short summary of the repair
                  description:
                    type: string
                    description: The detailed description of the repair
                  assignedTo:
                    type: string
                    description: The user who is responsible for the repair
                  details:
                    type: object
                    description: Additional details about the repair
                    properties:
                      partNumber:
                        type: string
                        description: The part number of the item to be repaired
                      warranty:
                        type: boolean
                        description: Whether the item is under warranty